version: '1'

services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MARIADB_DATABASE: bitnami_myapp
      MARIADB_USER: bn_myapp
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - laravel-network

  laravel:
    image: bitnami/laravel:latest
    container_name: laravel
    depends_on:
      - mariadb
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: bitnami_myapp
      LARAVEL_DB_USERNAME: bn_myapp
    volumes:
      - ./:/app
    networks:
      - laravel-network

volumes:
  mariadb_data:

networks:
  laravel-network:
    driver: bridge

